# Site
name: 'Kubernetes Mail Server'
description: 'A Dovecot/Postfix/OpenDKIM enabled Mail Server which runs on a Kubernetes Cluster'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'chris.thomas@antimatter-studios.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    chris:
      name:           Chris Thomas
      site:           https://antimatter-studios.com
      avatar:         https://s.gravatar.com/avatar/77249810e4f87e8a76d5f80f62cb869b?s=320
      bio:            "I'm a Software Engineer living in Berlin. I love all things Docker!"
      email:          chris.thomas@antimatter-studios.com
      twitter:        https://linkedin.com/in/chrisalexthomas

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]